In [7]:
#7
import numpy as np
arr1=np.array([[[1,2],[3,4],[5,6]]])
arr2 = np.array([[[7,8],[9,10],[11,12]]])
arr3=np.concatenate((arr1,arr2))
arr3=np.reshape(arr3,(2,2,3))
print(arr3)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:

#8
linear=np.linspace(0,20,6)
print(linear)

#9
import copy
copy_linear=copy.deepcopy(linear)


[ 0.  4.  8. 12. 16. 20.]


In [9]:
#10
newArray=np.concatenate((([[25, 16]]),([[11, 2], [13, 4]]),([[7, 81], [5, 6], [11, 12]])),axis=0)
print(newArray)
## 11
newArray=np.sort(newArray)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [10]:
#12
arr3=np.reshape(arr3,(2,2,3))
a,b = arr3
small, medium = a
large, xl = b
print(small)
print(medium)
print(large)
print(xl)


[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [11]:
#13
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
comboArray=np.concatenate((one,two,three))
comboArray=np.sort(comboArray)
print(comboArray)

#14
sec1=comboArray[1]
print(sec1)

sec2=comboArray[2:]
print(sec2)


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [12]:

sec3=comboArray[3:14]
print(sec3)

sec4=comboArray[-6:]
print(sec4)

sec5=comboArray[:-10]
print(sec5)

sec6=comboArray[16::2]
print(sec6)

sec7=comboArray[-1::5]
print(sec7)

[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27]


In [13]:
#15
import pandas as pd
ingredients = pd.Series(["Flour","Milk","Eggs","Spam"],name="Ingredients")
quantity = pd.Series([4,1,2,1],name="Quantity")
unit=pd.Series(["cups","cup","large","can"],name="Unit")
dinner = pd.concat([ingredients,quantity,unit],axis=1)
print(dinner)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [18]:
#16
studentData= {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
studentData=pd.DataFrame(studentData,columns=['Name','Height','Qualification','Address','Age','Pets','Sport'])
print(studentData)

      Name  Height Qualification  Address  Age        Pets Sport
0      Jai     5.1           Msc    Delhi   21         Dog   NaN
1  janusha     6.2            MA     Doha   23       Bunny   NaN
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla   NaN
3     Anuj     5.2           Msc   Dakhar   21      Parrot   NaN


In [21]:
#17
Desserts=["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['Desserts']=Desserts
print(studentData)

#18
studentData.sort_values(by = ['Name', 'Address'],
                ascending = [True, True], inplace = True)

      Name  Height Qualification  Address  Age        Pets Sport      Desserts
1  janusha     6.2            MA     Doha   23       Bunny   NaN     ice cream
0      Jai     5.1           Msc    Delhi   21         Dog   NaN  Cashew Fudge
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla   NaN       waffels
3     Anuj     5.2           Msc   Dakhar   21      Parrot   NaN  Carrot Halwa


In [31]:
#19
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])


df.to_csv('cows_and_goats.csv', index=False)

In [38]:
#20
vegetables = ({"Name":["Carrot","Broccoli","Peas"],
                "Color":["Orange","Green","Green"],
                "AmountEaten":[10,8,5]})
Veggies=pd.DataFrame(vegetables,columns=['Name','Color','AmountEaten'])
print(Veggies)

Veggies.to_csv('vegetables.csv', index=False)
Vegetables=pd.read_csv('vegetables.csv')
Ranking =[2,1,3]
Veggies.to_csv('vegetables_new.csv', index=False)



       Name   Color  AmountEaten
0    Carrot  Orange           10
1  Broccoli   Green            8
2      Peas   Green            5
